services:
  mongodb:
    image: mongo:6
    container_name: auction-mongodb

  backend:
    image: harshhdockerhub/auction-backend:latest
    container_name: auction-backend
    ports:
      - "5000:8080"   # host:container
    environment:
      - MONGODB_URI=mongodb://auction-mongodb:27017/auctiondb
    depends_on:
      - mongodb

  frontend:
    image: harshhdockerhub/auction-frontend:latest
    container_name: auction-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

