version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: auction-mongodb
    ports:
      - "27017:27017"
    networks:
      - auction-network

  backend:
    image: harshhdockerhub/auction-backend:latest
    container_name: auction-backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/auctiondb
      - PORT=5000
      - JWT_SECRET=your_jwt_secret
      - ORIGIN=http://localhost
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - auction-network

  frontend:
    image: harshhdockerhub/auction-frontend:latest
    container_name: auction-frontend
    environment:
      - BACKEND_URL=http://backend:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge
